import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Container from "./components/container";
import BottomNavbar from "./components/bottomnavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Schmeckle Telegram Bot",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Container>
               <div className="main relative z-20 h-full flex flex-col justify-between">
                  {children}
               </div>
            </Container>
            <script
               src="https://telegram.org/js/telegram-web-app.js"
               async
            ></script>
         </body>
      </html>
   );
}
